from __future__ import annotations

from pathlib import Path

from ..filesystem import copy_skill_bundle, ensure_dir, reset_dir, write_text_if_changed
from ..models import Repository


def build(repo: Repository) -> list[Path]:
    target_root = repo.root / "dist" / "claude"
    reset_dir(target_root)
    changed: list[Path] = []
    claude_root = target_root / ".claude"
    skills_dir = claude_root / "skills"
    readme_path = target_root / "CLAUDE.md"
    changed.append(readme_path)
    for skill in sorted(repo.skills.values(), key=lambda item: item.id):
        if "claude" not in skill.enabled_targets:
            continue
        dest = skills_dir / skill.id
        ensure_dir(dest)
        changed.extend(copy_skill_bundle(skill, dest))
    write_text_if_changed(readme_path, render_claude_readme(repo))
    return changed


def render_claude_readme(repo: Repository) -> str:
    lines = [
        "# Generated Claude Code Output",
        "",
        "This file is generated by `skillctl`. Do not edit it directly.",
        "",
        "Install into your project:",
        "",
        "```bash",
        "cp -R dist/claude/.claude /path/to/your-project/.claude",
        "```",
        "",
        "Personal install (all projects):",
        "",
        "```bash",
        "cp -R dist/claude/.claude/skills/* ~/.claude/skills/",
        "```",
        "",
        "Layout:",
        "",
        "- `.claude/skills/<skill-id>/SKILL.md` is the source of truth for workflow and output.",
        "- `.claude/skills/<skill-id>/references/` holds code samples and detailed guidance.",
        "- Optional `scripts/` and `assets/` live inside the same skill folder.",
        "",
        "Claude Code discovers skills from project `.claude/skills/` or user `~/.claude/skills/`.",
        "See https://code.claude.com/docs/en/skills",
        "",
        "## Skills",
        "",
    ]
    for skill in sorted(repo.skills.values(), key=lambda item: item.id):
        if "claude" in skill.enabled_targets:
            lines.append(f"- `{skill.id}`: {skill.summary}")
    return "\n".join(lines)
