from __future__ import annotations

from pathlib import Path

from ..filesystem import copy_skill_bundle, ensure_dir, reset_dir, write_text_if_changed
from ..models import Repository


def build(repo: Repository) -> list[Path]:
    target_root = repo.root / "dist" / "codex"
    reset_dir(target_root)
    changed: list[Path] = []
    readme_path = target_root / "AGENTS.md"
    changed.append(readme_path)
    for skill in sorted(repo.skills.values(), key=lambda item: item.id):
        if "codex" not in skill.enabled_targets:
            continue
        dest = target_root / "skills" / skill.id
        ensure_dir(dest)
        changed.extend(copy_skill_bundle(skill, dest))
    write_text_if_changed(readme_path, render_agents(repo))
    return changed


def render_agents(repo: Repository) -> str:
    lines = [
        "# Generated Codex Output",
        "",
        "This file is generated by `skillctl`. Do not edit it directly.",
        "",
        "Install into your project or agent workspace:",
        "",
        "```bash",
        "cp -R dist/codex/skills /path/to/your-project/skills",
        "```",
        "",
        "Layout:",
        "",
        "- `skills/<skill-id>/SKILL.md` is the source of truth for workflow and output.",
        "- `skills/<skill-id>/references/` holds code samples and detailed guidance.",
        "- Optional `scripts/` and `assets/` live inside the same skill folder.",
        "",
        "Codex and generic agents use skill bundles directly. Cursor and Copilot add thin routing files that point here.",
        "",
        "This is the portable skill bundle format. Other vendor outputs are adapters around the same source content.",
        "",
        "## Skills",
        "",
    ]
    for skill in sorted(repo.skills.values(), key=lambda item: item.id):
        if "codex" in skill.enabled_targets:
            lines.append(f"- `{skill.id}`: {skill.summary}")
    return "\n".join(lines)
