from __future__ import annotations

from ..filesystem import copy_skill_bundle, reset_dir, write_text_if_changed
from ..models import Repository, Skill
from ..routing import render_thin_routing_body


def build(repo: Repository) -> list[Path]:
    target_root = repo.root / "dist" / "copilot"
    reset_dir(target_root)
    changed: list[Path] = []
    github_root = target_root / ".github"
    instructions_dir = github_root / "instructions"
    skills_dir = github_root / "skills"
    for skill in sorted(repo.skills.values(), key=lambda item: item.id):
        if "copilot" not in skill.enabled_targets:
            continue
        instruction_path = instructions_dir / f"{skill.id}.instructions.md"
        if write_text_if_changed(instruction_path, render_skill_instruction(skill)):
            changed.append(instruction_path)
        changed.extend(copy_skill_bundle(skill, skills_dir / skill.id))

    repo_instruction = github_root / "copilot-instructions.md"
    if write_text_if_changed(repo_instruction, render_repository_instructions(repo)):
        changed.append(repo_instruction)

    agents_path = target_root / "AGENTS.md"
    if write_text_if_changed(agents_path, render_agents(repo)):
        changed.append(agents_path)
    return changed


def render_skill_instruction(skill: Skill) -> str:
    bundle_root = f".github/skills/{skill.id}"
    body = render_thin_routing_body(skill, bundle_root)
    return f"""---
applyTo: "**/*"
---

<!-- Generated by skillctl. Do not edit directly. -->

{body}
"""


def render_repository_instructions(repo: Repository) -> str:
    lines = [
        "# Generated Copilot Instructions",
        "",
        "This file is generated by `skillctl`. Do not edit it directly.",
        "",
        "Install into your project:",
        "",
        "```bash",
        "cp -R dist/copilot/.github /path/to/your-project/.github",
        "```",
        "",
        "Layout:",
        "",
        "- `.github/skills/<skill-id>/SKILL.md` is the source of truth for workflow and output.",
        "- `.github/skills/<skill-id>/references/` holds code samples and detailed guidance.",
        "- `.github/instructions/<skill-id>.instructions.md` is a thin router that points to the skill bundle.",
        "",
        "## Available Skills",
        "",
    ]
    for skill in sorted(repo.skills.values(), key=lambda item: item.id):
        if "copilot" in skill.enabled_targets:
            lines.append(
                f"- `{skill.id}`: `.github/skills/{skill.id}/SKILL.md` — {skill.summary}"
            )
    return "\n".join(lines)


def render_agents(repo: Repository) -> str:
    lines = [
        "# Generated Copilot Output",
        "",
        "This file is generated by `skillctl`. Do not edit it directly.",
        "",
        "Copy `dist/copilot/.github` into your repository.",
        "",
        "Skill bundles contain the workflow. Instruction files only route agents to those bundles.",
        "",
        "## Skills",
        "",
    ]
    for skill in sorted(repo.skills.values(), key=lambda item: item.id):
        if "copilot" in skill.enabled_targets:
            lines.append(
                f"- `{skill.id}`: `.github/skills/{skill.id}/SKILL.md` — {skill.summary}"
            )
    lines.extend(["", "## Instruction Routers", ""])
    for skill in sorted(repo.skills.values(), key=lambda item: item.id):
        if "copilot" in skill.enabled_targets:
            lines.append(
                f"- `{skill.id}.instructions.md`: routes to `.github/skills/{skill.id}/`"
            )
    return "\n".join(lines)
