from __future__ import annotations

from ..filesystem import copy_skill_bundle, reset_dir, write_text_if_changed
from ..models import Repository, Skill
from ..routing import render_thin_routing_body


def build(repo: Repository) -> list[Path]:
    target_root = repo.root / "dist" / "cursor"
    reset_dir(target_root)
    changed: list[Path] = []
    cursor_root = target_root / ".cursor"
    rules_dir = cursor_root / "rules"
    skills_dir = cursor_root / "skills"
    for skill in sorted(repo.skills.values(), key=lambda item: item.id):
        if "cursor" not in skill.enabled_targets:
            continue
        rule_path = rules_dir / f"{skill.id}.mdc"
        if write_text_if_changed(rule_path, render_rule(skill)):
            changed.append(rule_path)
        changed.extend(copy_skill_bundle(skill, skills_dir / skill.id))
    agents_path = target_root / "AGENTS.md"
    if write_text_if_changed(agents_path, render_agents(repo)):
        changed.append(agents_path)
    return changed


def render_rule(skill: Skill) -> str:
    bundle_root = f".cursor/skills/{skill.id}"
    body = render_thin_routing_body(skill, bundle_root)
    return f"""---
description: {skill.summary}
alwaysApply: false
---

<!-- Generated by skillctl. Do not edit directly. -->

{body}
"""


def render_agents(repo: Repository) -> str:
    lines = [
        "# Generated Cursor Output",
        "",
        "This file is generated by `skillctl`. Do not edit it directly.",
        "",
        "Install into your project:",
        "",
        "```bash",
        "cp -R dist/cursor/.cursor /path/to/your-project/.cursor",
        "```",
        "",
        "Layout:",
        "",
        "- `.cursor/skills/<skill-id>/SKILL.md` is the source of truth for workflow and output.",
        "- `.cursor/skills/<skill-id>/references/` holds code samples and detailed guidance.",
        "- `.cursor/rules/<skill-id>.mdc` is a thin router that points to the skill bundle.",
        "",
        "Do not edit generated files directly. Change canonical skills under `skills/` in agent-skills.",
        "",
        "## Skills",
        "",
    ]
    for skill in sorted(repo.skills.values(), key=lambda item: item.id):
        if "cursor" in skill.enabled_targets:
            lines.append(
                f"- `{skill.id}`: `.cursor/skills/{skill.id}/SKILL.md` — {skill.summary}"
            )
    lines.extend(["", "## Rules", ""])
    for skill in sorted(repo.skills.values(), key=lambda item: item.id):
        if "cursor" in skill.enabled_targets:
            lines.append(f"- `{skill.id}.mdc`: routes to `.cursor/skills/{skill.id}/`")
    return "\n".join(lines)
