from __future__ import annotations

from pathlib import Path

from ..filesystem import copy_skill_bundle, ensure_dir, reset_dir, write_text_if_changed
from ..models import Repository


def build(repo: Repository) -> list[Path]:
    target_root = repo.root / "dist" / "opencode"
    reset_dir(target_root)
    changed: list[Path] = []
    opencode_root = target_root / ".opencode"
    skills_dir = opencode_root / "skills"
    readme_path = target_root / "AGENTS.md"
    changed.append(readme_path)
    for skill in sorted(repo.skills.values(), key=lambda item: item.id):
        if "opencode" not in skill.enabled_targets:
            continue
        dest = skills_dir / skill.id
        ensure_dir(dest)
        changed.extend(copy_skill_bundle(skill, dest))
    write_text_if_changed(readme_path, render_agents_readme(repo))
    return changed


def render_agents_readme(repo: Repository) -> str:
    lines = [
        "# Generated OpenCode Output",
        "",
        "This file is generated by `skillctl`. Do not edit it directly.",
        "",
        "Install into your project:",
        "",
        "```bash",
        "cp -R dist/opencode/.opencode /path/to/your-project/.opencode",
        "```",
        "",
        "Global install (all projects):",
        "",
        "```bash",
        "mkdir -p ~/.config/opencode/skills",
        "cp -R dist/opencode/.opencode/skills/* ~/.config/opencode/skills/",
        "```",
        "",
        "Layout:",
        "",
        "- `.opencode/skills/<skill-id>/SKILL.md` is the source of truth for workflow and output.",
        "- `.opencode/skills/<skill-id>/references/` holds code samples and detailed guidance.",
        "- Optional `scripts/` and `assets/` live inside the same skill folder.",
        "",
        "OpenCode discovers skills from project `.opencode/skills/`, `.claude/skills/`, or",
        "`.agents/skills/` (and global `~/.config/opencode/skills/`). Skills load on demand via",
        "the native `skill` tool. See https://opencode.ai/docs/skills/",
        "",
        "If your project already has an `AGENTS.md`, merge any relevant sections from this",
        "generated index — do not replace your project rules file blindly.",
        "",
        "## Skills",
        "",
    ]
    for skill in sorted(repo.skills.values(), key=lambda item: item.id):
        if "opencode" in skill.enabled_targets:
            lines.append(f"- `{skill.id}`: {skill.summary}")
    return "\n".join(lines)
